version: '3'

services:
  app:
    command: npm run start
    restart: always
    ports:
      - "4001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/bcrypt/
    env_file: ./env/staging.env

  mongo:
    volumes:
      - /home/marketx_id/marketx_data_staging:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  
  mongo2:
    volumes: 
      - /home/marketx_id/marketx_data2_staging:/data/db