version: '3'

services:
  app:
    build: .
    depends_on:
      - mongo
      - redis

  mongo:
    hostname: mongo
    image: mongo:4.4.1
    restart: always
    expose:
      - 27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    hostname: mongo2
    image: mongo:4.4.1
    restart: always
    expose:
      - 27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  
  mongosetup:
    image: mongo:4.4.1
    depends_on:
      - mongo
      - mongo2
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]
  
  redis:
    restart: always
    image: redis:alpine