version: '3'

services:
  app:
    command: npm run dev
    ports:
      - "4000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/bcrypt/
    env_file: ./env/dev.env
  
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  mongo:
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  
  mongo2:
    volumes: 
      - mongodata2:/data/db

  populate_data:
    command: /bin/bash -c "sleep 60 && mysql -h mysql -u ${MYSQL_USER} --password=${MYSQL_PASSWORD} --database ${MYSQL_DATABASE} < /administrative_area.sql"

volumes:
  mongodata:
  mongodata2:
  mysqldata:
    