version: '3'

services:
  app:
    build: .
    depends_on:
      - mongo
      - redis

  mongo:
    hostname: mongo
    image: mongo:4.4.1
    restart: always
    expose:
      - 27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    hostname: mongo2
    image: mongo:4.4.1
    restart: always
    expose:
      - 27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  
  mongosetup:
    image: mongo:4.4.1
    depends_on:
      - mongo
      - mongo2
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]
  
  redis:
    restart: always
    image: redis:alpine

  mysql:
    image: "mysql:8.0.15"
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password

  populate_data:
    image: mysql:8.0.15
    depends_on:
      - mysql
    volumes:
      - ./database/sql/administrative_area.sql:/administrative_area.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - 8080:80