version: '3'

services:
  app:
    command: npm run start
    restart: always
    ports:
      - "4001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/bcrypt/
    env_file: ./env/staging.env

  mongo:
    volumes:
      - staging_mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rental_app
  
  mongo2:
    volumes: 
      - staging_mongodata2:/data/db
      
volumes:
  staging_mongodata:
  staging_mongodata2: